export const savedData = [
  {
    id: 1,
    img: "https://static.live.templately.com/2021/06/297c6a78-image0.png",
    product: "Python Class",
    stock: "In Stock",
    price: 20,
  },
  {
    id: 2,
    img: "https://static.live.templately.com/2021/06/297c6a78-image0.png",
    product: "Python Class",
    stock: "In Stock",
    price: 20,
  },
  {
    id: 3,
    img: "https://static.live.templately.com/2021/06/297c6a78-image0.png",
    product: "Python Class",
    stock: "In Stock",
    price: 20,
  },
  {
    id: 4,
    img: "https://static.live.templately.com/2021/06/297c6a78-image0.png",
    product: "Python Class",
    stock: "In Stock",
    price: 20,
  },
];

export const transactionData = [
  {
    id: 1143155,
    product: "Acer Nitro 5",
    img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
    customer: "John Smith",
    date: "1 March",
    amount: 785,
    method: "Cash on Delivery",
    status: "Approved",
  },
  {
    id: 2235235,
    product: "Playstation 5",
    img: "https://m.media-amazon.com/images/I/31JaiPXYI8L._AC_UY327_FMwebp_QL65_.jpg",
    customer: "Michael Doe",
    date: "1 March",
    amount: 900,
    method: "Online Payment",
    status: "Pending",
  },
  {
    id: 2342353,
    product: "Redragon S101",
    img: "https://m.media-amazon.com/images/I/71kr3WAj1FL._AC_UY327_FMwebp_QL65_.jpg",
    customer: "John Smith",
    date: "1 March",
    amount: 35,
    method: "Cash on Delivery",
    status: "Pending",
  },
  {
    id: 2357741,
    product: "Razer Blade 15",
    img: "https://m.media-amazon.com/images/I/71wF7YDIQkL._AC_UY327_FMwebp_QL65_.jpg",
    customer: "Jane Smith",
    date: "1 March",
    amount: 920,
    method: "Online",
    status: "Approved",
  },
  {
    id: 2342355,
    product: "ASUS ROG Strix",
    img: "https://m.media-amazon.com/images/I/81hH5vK-MCL._AC_UY327_FMwebp_QL65_.jpg",
    customer: "Harold Carol",
    date: "1 March",
    amount: 2000,
    method: "Online",
    status: "Pending",
  },
];
